import torch
from torch import nn


class MatchMask(nn.Module):
    """
    Args:
        features: K attention maps generated by 1×1 convolution and Softmax
        targets: human parsing results
    """

    def __init__(self):
        super(MatchMask, self).__init__()

    def forward(self, inputs, targets):
        mask = torch.zeros_like(inputs)
        for i in range(inputs.shape[0]):
            mask[i][0][(targets[i] == 1)] = 1
            mask[i][1][(targets[i] == 2) | (targets[i] == 5) | (targets[i] == 9)] = 1
            mask[i][2][(targets[i] == 3) | (targets[i] == 4) | (targets[i] == 6) | (targets[i] == 8)] = 1
            mask[i][3][(targets[i] == 7)] = 1

        res = -(inputs.clamp(min=1e-8).log() * mask).mean(dim=(2, 3)).sum(dim=1).mean(dim=0)
        return res
